### PR TITLE
[ADD] card_installment

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/301).

**Comment by bruno-zanotti** [comment]
@roboadhoc rebase-ff r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request merged**
