### PR TITLE
[WIP]

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/548).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @rov-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@jjscarafia @rov-adhoc linked pull request(s) ingadhoc/odoo-argentina#935 not ready. Linked PRs are not staged until all of them are ready.

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
