### PR TITLE
[FIX] account_payment_group: default to_pay_move_line_ids

### PR DESCRIPTION
**Pull request by ica-adhoc**
ticket 58022

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/340).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by zaoral** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by zaoral** [comment]
we override the status because we have a warning in build all that is already in branch 15.0 and is not related to this change

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Comment by fw-bot-adhoc** [comment]
@ica-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#341

**Pull request closed without merging**
