### PR TITLE
[FW][FIX] account_payment_group: remove not from sequence filter

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-payment#511

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/513).

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc cherrypicking of pull request ingadhoc/account-payment#511 failed.

stdout:
```
CONFLICT (modify/delete): account_payment_group/models/account_move.py deleted in HEAD and modified in 92935420 ([FIX] account_payment_group: remove not from sequence filter). Version 92935420 ([FIX] account_payment_group: remove not from sequence filter) of account_payment_group/models/account_move.py left in tree.

```

stderr:
```
15:06:10.088583 git.c:444               trace: built-in: git cherry-pick 9293542017dd41da4aecafe07511ef2eb1106baf
error: could not apply 92935420... [FIX] account_payment_group: remove not from sequence filter
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Comment by cav-adhoc** [comment]
Sigue en https://github.com/ingadhoc/account-payment/pull/512

**Pull request closed without merging**
