### PR TITLE
[ADD] account_payment_group_financial_surcharge: compatibility with AR EDI

### PR DESCRIPTION
**Pull request by zaoral**
Add conext key in order to be used to identify and auto complete missing fields required for EDI

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/349).

**Comment by zaoral** [comment]
@roboadhoc rebase-ff
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral:
- you can't method=rebase-ff.
- you can't review+.

**Comment by zaoral** [comment]
@nicomacr Hi Nico
Please coukld you help me with this pr , the merge is telling me  "you can't method=rebase-ff."

**Comment by ica-adhoc** [comment]
@roboadhoc rebase-ff
@roboadhoc r+

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
