### PR TITLE
[IMP] Add readme

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/558).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
