### PR TITLE
[FW][REF] account_payment_pro: refactoring of the action_payment_register method

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
… method

Forward-Port-Of: ingadhoc/account-payment#572

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/573).

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by feg-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
