### PR TITLE
[ADD] add new module account_payment_multi to create payment links fo…

### PR DESCRIPTION
**Pull request by maq-adhoc**
…r multiples invoices

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/365).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#370

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#370

**Pull request closed without merging**
