### PR TITLE
[IMP] account_payment_invoice: refact method  create_electronic_payment

### PR DESCRIPTION
**Pull request by maq-adhoc**
create and send request inside a try

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/426).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#427

**Pull request closed without merging**
