### PR TITLE
[FW][IMP] Cashbox updates

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-payment#470

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/474).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia cherrypicking of pull request ingadhoc/account-payment#470 failed.

* 71e1dbf2568fd5582b4e1cfca2c3311caebc55b1 <- on this commit
* 8c402edfb8ce74145eda28f1d804df52af974d35
* 190a42d83f2b6a067e5a9128c9106da0da3cc07f
* bf32f89c8ace007485d0b2ff91e294ce2dc51afb

stdout:
```
Auto-merging account_cashbox_l10n_latam_check/wizards/l10n_latam_payment_mass_transfer_views.xml
CONFLICT (content): Merge conflict in account_cashbox_l10n_latam_check/wizards/l10n_latam_payment_mass_transfer_views.xml
Auto-merging account_cashbox_l10n_latam_check/wizards/l10n_latam_payment_mass_transfer.py
Auto-merging account_cashbox/views/account_payment.xml
CONFLICT (content): Merge conflict in account_cashbox/views/account_payment.xml
Auto-merging account_cashbox/views/account_cashbox_session.xml
Auto-merging account_cashbox/views/account_cashbox.xml
CONFLICT (content): Merge conflict in account_cashbox/views/account_cashbox.xml
Auto-merging account_cashbox/models/account_cashbox_session.py
CONFLICT (content): Merge conflict in account_cashbox/models/account_cashbox_session.py
Auto-merging account_cashbox/models/account_cashbox.py

```

stderr:
```
14:44:37.709350 git.c:444               trace: built-in: git cherry-pick 71e1dbf2568fd5582b4e1cfca2c3311caebc55b1
error: could not apply 71e1dbf2... [IMP] Cashbox updates
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@maq-adhoc @jjscarafia unable to stage: All commits must have author and committer email, missing email on e10903c650163f6073a5661b04ab2912e50ecaf9 indicates the authorship is most likely incorrect.

**Pull request merged**
