### PR TITLE
[FW][IMP] account_payment_invoice: refact method  create_electronic_payment

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
create and send request inside a try

Forward-Port-Of: ingadhoc/account-payment#426

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/427).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Pull request closed without merging**
