### PR TITLE
[FW][FIX] account_cashbox: Clear the field of allowed_res_users_ids when the restrict_users is not set

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-payment#504

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/506).

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @maq-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @maq-adhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @maq-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
