### PR TITLE
[15.0] [FIX] account_payment_group: For cancel invoice we remove pay_now_journal_id

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/256).

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by nicomacr** [comment]
@roboadhoc r-

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. r- makes no sense in the current PR state.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc review+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
