### PR TITLE
[FIX] _group: fix default_company sent to pay lines

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/489).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
@fw-bot-adhoc ignore

**Comment by fw-bot-adhoc** [comment]
Forward-port disabled.

**Pull request closed without merging**
