### PR TITLE
[FIX] card_installment: Change demo data and usage specification

### PR DESCRIPTION
**Pull request by feg-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/566).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
