### PR TITLE
[FIX] account_payment_group: sequences

### PR DESCRIPTION
**Pull request by zaoral**
Do different seq when move related to payment group, if not use the journal regular sequence.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/309).

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Comment by jjscarafia** [comment]
se mezcla igual porque el error de runbot NO tiene que ver con este PR

**Pull request merged**
