### PR TITLE
[IMP] _pro_receiptbook: archived receiptboks use cases

### PR DESCRIPTION
**Pull request by jjscarafia**
1. Mejoramos para que si el talonario esta archivado no deje consumir número (es para caso de uruguay donde los talonarios de recibos manuales existen y son legales y tienen que tener control de la numeración)
2. Agregamos el open de receipbook para poder ir rápidamente al mismo si es necesario

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/579).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#580

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#580

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#580

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#580

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#580

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#580

**Pull request closed without merging**
