### PR TITLE
[FW][IMP] account_payment_group:order imputed invoices by date maturity and move name on receipts

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 52918

Forward-Port-Of: ingadhoc/account-payment#336

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/338).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @ica-adhoc cherrypicking of pull request ingadhoc/account-payment#336 failed.

stdout:
```
Auto-merging account_payment_group/models/account_payment_group.py
CONFLICT (content): Merge conflict in account_payment_group/models/account_payment_group.py

```

stderr:
```
12:58:02.737613 git.c:439               trace: built-in: git cherry-pick 11a1163e8b018aaa78681a093bfb47b4ec737cb3
error: could not apply 11a1163e... [IMP] account_payment_group:order imputed invoices by date maturity and move name on receipts
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/338).

**Comment by nicomacr** [comment]
@ica-adhoc @pablohmontenegro  please check this PR and try to have all tests on the green to merge

**Comment by pablohmontenegro** [comment]
Closed bacause was already incorporated here https://github.com/ingadhoc/account-payment/pull/325

**Pull request closed without merging**
