### PR TITLE
[FW][ADD] add new module account_cashbox_l10n_latam_check

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Agrego un modulo puente para registrar la sesión en la transferencia de cheques

Forward-Port-Of: ingadhoc/account-payment#414

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/434).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia ci/runbot-oba failed on this forward-port PR

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
