### PR TITLE
[FW][FIX] account_withholding: error al calcular retenciones en pago a proveedor

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Ticket: 67203

Forward-Port-Of: ingadhoc/account-payment#408

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/409).

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by pablohmontenegro** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@pablohmontenegro @nicomacr this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by zaoral** [comment]
@roboadhoc) r+

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba
@roboadhoc r+

**Pull request merged**
