### PR TITLE
[FW][FIX] Fix Transsacctions in installment

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-payment#388

### CODE REVIEW

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/428).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Pull request closed without merging**
