### PR TITLE
[IMP] add cashbox suport to modules that use payment register

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/514).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#518

**Pull request closed without merging**
