### PR TITLE
[FW][IMP] set False  in group of bank and cash menu

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-payment#433

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/455).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @rov-adhoc cherrypicking of pull request ingadhoc/account-payment#433 failed.

stdout:
```
Auto-merging account_cashbox/__manifest__.py
CONFLICT (content): Merge conflict in account_cashbox/__manifest__.py

```

stderr:
```
13:11:16.699887 git.c:444               trace: built-in: git cherry-pick d21e89f58e91bf03cbeb3abb09a57d26928c30b1
error: could not apply d21e89f5... [IMP] link account.group_account_user  in groups_id of bank and cash menu and transfer
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by rov-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc I can only do this on unmodified forward-port PRs, ask roboadhoc.

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
