### PR TITLE
[FIX] account_payment_group_document: Default receiptbook on payment groups

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/372).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you can't review+.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#373

**Comment by fw-bot-adhoc** [comment]
@zaoral @pablohmontenegro this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#373

**Pull request closed without merging**
