### PR TITLE
[IMP]account_payment_group:Se forma el metodo pay_now_context fuera del metodo pay_now

### PR DESCRIPTION
**Pull request by mem-adhoc**
Ticket:52972

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/318).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Comment by fw-bot-adhoc** [comment]
@mem-adhoc @zaoral this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/account-payment#327
- ingadhoc/account-payment#328

**Pull request closed without merging**
