### PR TITLE
[FW][ADD] add new module account_payment_multi to create payment links fo…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…r multiples invoices

Forward-Port-Of: ingadhoc/account-payment#365

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/370).

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@maq-adhoc @augusto-weiss this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Pull request closed without merging**
