### PR TITLE
[REF] latam_check: MAJOR update from odoo PR

### PR DESCRIPTION
**Pull request by jjscarafia**
IMPORTANTE: este cambio no es actualizable, faltarian scripts de migracion

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/282).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=1

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
