### PR TITLE
[FIX] account_cashbox: Clear the field of allowed_res_users_ids when the restrict_users is not set

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/504).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#506

**Comment by fw-bot-adhoc** [comment]
@rov-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#506

**Pull request closed without merging**
