### PR TITLE
[FIX] Fix visibility of default_account_id in general journal

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/399).

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Review by pablohmontenegro — APPROVED** [review]

**Comment by pablohmontenegro** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: you are not allowed to override this status.

**Pull request merged**
