### PR TITLE
[ADD] account_payment_pro_receiptbook: Added multi-company rule

### PR DESCRIPTION
**Pull request by feg-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/509).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @rov-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by roboadhoc** [comment]
@feg-adhoc @rov-adhoc linked pull request(s) ingadhoc/odoo-argentina-ee#446 not ready. Linked PRs are not staged until all of them are ready.

**Comment by roboadhoc** [comment]
@feg-adhoc @rov-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by cav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @cav-adhoc: this PR is already reviewed, reviewing it again is useless.

**Comment by cav-adhoc** [comment]
@roboadhoc  r+

**Pull request closed without merging**
