### PR TITLE
[FIX] financial_surcharge: multiple fixes

### PR DESCRIPTION
**Pull request by zaoral**
task 29992

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/357).

**Review by pablohmontenegro — DISMISSED** [review]

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by pablohmontenegro** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral @pablohmontenegro because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by pablohmontenegro** [comment]
@roboadhoc r+ merge

**Comment by roboadhoc** [comment]
Merge method set to merge directly, using the PR as merge commit message.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: this PR is already reviewed, reviewing it again is useless.

**Review by pablohmontenegro — APPROVED** [review]

**Comment by pablohmontenegro** [comment]
@roboadhoc r+ merge

**Comment by roboadhoc** [comment]
Merge method set to merge directly, using the PR as merge commit message.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: this PR is already reviewed, reviewing it again is useless.

**Comment by pablohmontenegro** [comment]
@roboadhoc r+ merge

**Review by pablohmontenegro — APPROVED** [review]

**Comment by roboadhoc** [comment]
Merge method set to merge directly, using the PR as merge commit message.

**Comment by roboadhoc** [comment]
I'm sorry, @pablohmontenegro: this PR is already reviewed, reviewing it again is useless.

**Pull request merged**
