### PR TITLE
[IMP] account_cashbox: add bypass for journal currency

### PR DESCRIPTION
**Pull request by cav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/534).

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#535

**Comment by fw-bot-adhoc** [comment]
@cav-adhoc @rov-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#535

**Pull request closed without merging**
