### PR TITLE
[FW][IMP] account_payment_group: don't allow to re-post a payment group

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/account-payment#276

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/277).

**Comment by fw-bot-adhoc** [comment]
Ping @jjscarafia cherrypicking of pull request ingadhoc/account-payment#276 failed.

stdout:
```
Auto-merging account_payment_group/models/account_payment_group.py
CONFLICT (content): Merge conflict in account_payment_group/models/account_payment_group.py

```

stderr:
```
20:56:31.466511 git.c:439               trace: built-in: git cherry-pick 31e8941e5151269db870b3d03ee11c9e252cd2e0
error: could not apply 31e8941e... [IMP] account_payment_group: don't allow to re-post a payment group
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by jjscarafia** [comment]
@roboadhoc r+ merge

**Comment by roboadhoc** [comment]
Merge method set to merge directly, using the PR as merge commit message

**Pull request merged**
