### PR TITLE
[REF] account_payment_pro: refactoring of the action_payment_register method

### PR DESCRIPTION
**Pull request by feg-adhoc**
… method

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/572).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Comment by fw-bot-adhoc** [comment]
@feg-adhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/account-payment#573

**Pull request closed without merging**
