### PR TITLE
[REM] l10n_latam_check: Now we use official module

### PR DESCRIPTION
**Pull request by zaoral**
We delete this module because we are already using the version already in 16.0 odoo/odoo official repo.

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/account-payment/pull/315).

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by juanpgarza** [comment]
> We delete this module because we are already using the version already in 16.0 odoo/odoo official repo.

what is the name of the module in the official odoo repo? can't find it ...

**Comment by zaoral** [comment]
Hi @juanpgarza
Thank you for your message

The module has the same name, we are waiting for Odoo team to merge it in the next days.
Leave you here the pr with the module https://github.com/odoo/odoo/pull/96074

Best Regards

**Pull request closed without merging**
