### PR TITLE
[ADD] Add new module accout_payment_ux Fix the behavior of pending tr…

### PR DESCRIPTION
**Pull request by maq-adhoc**
…ansacition realated with a account.payment

	What is happening now:
		- when i'm create a electronic payment from backend and the transaction remains in pending status the payment status is changed to canceled what happens after installing this module
		- When the transaction is pending the payment remains in draft status. After done this transaction the payment change its state ans reconcilie with the invoices

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/379).

**Comment by nicomacr** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@maq-adhoc @nicomacr unable to stage: commits with multiple parents (41845619ca3476b44adc3fa08f8fbc1e3c638b0c) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Pull request closed without merging**
