### PR TITLE
[IMP] fix label for default account in journal general

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/account-payment/pull/395).

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Comment by ica-adhoc** [comment]
@roboadhoc r-

**Comment by roboadhoc** [comment]
I'm sorry, @ica-adhoc: r- makes no sense in the current PR state.

**Review by ica-adhoc — APPROVED** [review]

**Comment by ica-adhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @ica-adhoc: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by jjscarafia** [comment]
mezclamos igual ya que es un warning y no relativo a este modulo

**Pull request merged**
